### ISSUE TITLE
how can i delete existing api chat history

### ISSUE THREAD

**Issue by schxar** [TREE-Ind/Blender-GPT#1]
![image](https://user-images.githubusercontent.com/65155656/228024333-9bd94b46-7f0c-4a9e-8832-7a987e4bf285.png)

I can`t access that , soon reach token limit, how can i delete all talk history? there should be a file or a setting button to delete it
and why it has the right to reset my all plugin
![image](https://user-images.githubusercontent.com/65155656/228024619-12e1b7c6-91d6-46a0-9e9f-c0008e3ffe84.png)

![image](https://user-images.githubusercontent.com/65155656/228024824-60b70787-37fb-4ea3-b80c-c8551ee37e81.png)

**Comment by schxar** [comment]
![image](https://user-images.githubusercontent.com/65155656/228025390-1bd08010-fbde-4aa5-8048-005d2c3a7cf9.png)
oh my god what the hell it is doing 
using whisper voice to edit plane and some random Japanese test show up and change my blender scene

**Comment by schxar** [comment]
![image](https://user-images.githubusercontent.com/65155656/228027196-cdec185b-ecd2-4296-8647-7f86c5e52911.png)
need a little improvement
 but it worked, it give me a snowball

**Comment by schxar** [comment]
![image](https://user-images.githubusercontent.com/65155656/228027719-cc87cfb5-7761-461b-9feb-e2b3b4778e79.png)
no , it can't generate something has a rigged bone

**Comment by TREE-Ind** [comment]
Update coming shortly to clear chat history, as well as adding the ability to copy and paste previous requests back into the input field.

Thanks so much for trying it out, hopefully we'll continue to improve as time allows.  Early days but it does seem like there is potential for these types of DCC AI assistants.

**Comment by TREE-Ind** [comment]
New version has been pushed so you can clear chat history now.  Closing for now, pls feel free to re-open if there is a major issue with the features, cheers.
